config/routes.rb
Rails.application.routes.draw do
  resources :news_blogs

  devise_for :users, path_names: {
    sign_up: '' #Stop Sign Up
  }
  devise_scope :user do
    get 'admin', to: 'devise/sessions#new'
  end

  get 'sitemap', to: 'sitemaps#index'

  get 'home', to: 'pages#home', as: 'home'
  get 'pharmacy', to: 'pages#pharmacy', as: 'pharmacy'
  get 'careproviders', to: 'pages#careproviders', as: 'careproviders'
  get 'faqs', to: 'pages#faqs', as: 'faqs'
  get 'news', to: 'pages#news', as: 'news'
  get 'news_show/:id', to: 'pages#news_show', as: 'show'
  get 'contactus', to: 'pages#contactus', as: 'contactus'
  get 'updates', to: 'pages#updates', as: 'updates'

  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  post 'contact-us', to: 'contacts#create', as: 'create_contact'

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  # attr_accessor :name, :email, :body
  attr_accessor :first_name, :last_name, :phone, :email, :body, :organization
  validates :first_name, :last_name, :phone, :email, :body, :organization, presence: true
end

app/models/news_blog.rb
class NewsBlog < ApplicationRecord
  has_many_attached :attachments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def hello
    render html: "Hello, World!"
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    #--- Send through SMTP ---#
    # @contact = Contact.new(contact_params)
    # if @contact.valid?
    #   MessageMailer.contact_me(@contact).deliver_now
    #   redirect_to request.referrer, notice: "Thank you, We will be in touch shortly!"
    # else
    #   render :new
    # end

    #--- Send through API ---#
    # @arr_with_hash = []
    # arr = []
    # contact_email_hash = {}
    # arr.each_with_index {|value, index| contact_email_hash[index] = value}
    @api_client = OnePageCRM.new(ENV['ONEPAGE_USER_EMAIL'], ENV['ONEPAGE_USER_PASS'])
    @contact = Contact.new(contact_params)
    if @contact.valid? && verify_recaptcha(model: @contact)
      # arr << @contact.email
      # arr.each_with_index {|value, index| contact_email_hash[index.to_s] = value}
      # @arr_with_hash << contact_email_hash
      # @api_client.post('contacts.json', {'last_name': @contact.name, 'emails': @arr_with_hash, 'background': @contact.body} )
      @new_contact = @api_client.post('contacts.json', {'first_name': @contact.first_name,
                                                        'last_name': @contact.last_name,
                                                        'company_name': @contact.organization,
                                                        'emails': [{ 'type' => 'work', 'value' => @contact.email}],
                                                        'phones': [{ 'type' => 'other', 'value' => @contact.phone}],
                                                        'background': @contact.body} )
      @contact_id = @new_contact["data"]["contact"]["id"]
      @new_action = @api_client.post('actions.json',
                      "assignee_id": "","contact_id": @contact_id,"date": "","done": false,"id": "","modified_at": "","status": "date","text": "New Lead created through the CAREMEDS Website!" )
      redirect_to request.referrer, notice: "Thank you, We will be in touch shortly!"
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone, :email, :body, :organization)
  end
end

app/controllers/news_blogs_controller.rb
class NewsBlogsController < ApplicationController
  before_action :set_news_blog, only: [:show, :edit, :update, :destroy]

  def index
    @news_blogs = NewsBlog.all
  end

  def new
    @news_blog = NewsBlog.new
  end

  def create
    @news_blog = NewsBlog.new(news_blog_params)
    if !@news_blog.attachments.attach.blank? == true
      @news_blog.attachments.attach(params[:news_blog][:attachments])
      @news_blog.save
      redirect_to news_blogs_path
      flash[:notice] = "News Blog successfully created!"
    else
      @news_blog.save
      redirect_to news_blogs_path
      flash[:notice] = "News Blog successfully created!"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @news_blog.update(news_blog_params)
      redirect_to news_blogs_path
      flash[:notice] = "News Blog successfully updated!"
    end
  end

  def destroy
    if @news_blog.destroy
      redirect_to news_blogs_path
      flash[:notice] = "News Blog successfully deleted!"
    end
  end

  private

  def set_news_blog
    @news_blog = NewsBlog.find(params[:id])
  end

  def news_blog_params
    params.require(:news_blog).permit(:title, :description, :meta_keywords, attachments: [] )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def pharmacy
  end

  def careproviders
  end

  def faqs
  end

  def news
    @news_blogs = NewsBlog.all
  end

  def news_show
    @news_blog = NewsBlog.find(params[:id])
    respond_to do |format|
      format.js { render layout: false}
    end
  end

  def contactus
  end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController

  def index
    @host = "#{request.protocol}#{request.host}"
    @news_blogs = NewsBlog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_keywords
    content_for?(:meta_keywords) ? content_for(:meta_keywords) : DEFAULT_META["meta_keywords"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    # meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contacts/new.html.erb
<%= render "shared/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'https://png.icons8.com/ios/55/156DB1/circled-C.png' %>
    <!-- <title><%#= yield(:title) %> | CareMeds</title> -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="keywords" content="<%= meta_keywords %>">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"> -->
    <!-- <%#= stylesheet_pack_tag 'application', media: 'all' %> Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%#= yield(:after_js) %>
  </body>
</html>

app/views/news_blogs/edit.html.erb
<%= render partial: 'news_blog' %>

app/views/news_blogs/new.html.erb
<%= render partial: "news_blog" %>

app/views/news_blogs/show.html.erb
<% content_for :meta_title, "#{@news_blog.title} | #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "#{@news_blog.description.truncate(150)}" %>
<% content_for :meta_keywords, "#{@news_blog.meta_keywords}" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <div class="news-item">
          <div class="title">
            <div class="news-date">
              <p class="created-day"><%= @news_blog.created_at.strftime("%e") %></p>
              <p class="created-month"><%= @news_blog.created_at.strftime("%b") %></p>
            </div>
              <h2 id="nb-title"><%= @news_blog.title %></h2>
              <p><%= link_to "Edit", edit_news_blog_path(@news_blog) %></p>|
              <p><%= link_to "Delete", news_blog_path(@news_blog), method: :delete, data: { confirm: "Are You Sure?"} %></p>
          </div>
          <hr style="border-color:#9d9d9d6b;margin:8px 0 8px 0;">
          <p class="news-info">Details</p>
          <p style="color:#778899"><%= @news_blog.description %></p>
          <div class="row" style="padding-bottom: 20px">
            <% counter = 0 %>
            <% if @news_blog.attachments.attachments != nil %>
              <% @news_blog.attachments.each do |a| %>
              <% counter += 1 %>
               <div class="-col-xs-12 col-sm-4">
                <div class="card-<%= counter %>">
                  <div class="card-image">
                    <%= image_tag a %>
                  </div>
                </div>
               </div>
              <% end %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>


<style>
  body {
    background-color:#fff;
  }

  .news-item  {
    border-bottom: 1px solid grey;
    margin-top:50px;
    margin-bottom:30px;
  }

  .title {
    display: flex;
    justify-content: space-between;
  }

  #nb-title {
    /*position: absolute;
    left: 100px;*/
    flex-grow: 2;
    color:#445d77;
  }

  .news-date {
    /*display: flex;*/
    /*flex-direction: column;*/
    /*border-right: 1px solid red;*/
    padding: 12px 15px;
    margin: 0px 15px 6px 0px;
    background: #1c60ad;
    border: 1px solid #2c97d2;
    color: white;
    border-radius: 10px;
  }

  .created-month {
    letter-spacing: 2px;
    text-align: center;
    font-size: 10px;
    text-transform: uppercase;
    line-height: 14px;
  }

  .created-day {
    font-size: 27px;
    letter-spacing: 0;
    text-align: center;
    line-height: 30px;
  }

  .news-info {
    /*display: inline;*/
    padding: 0px 12px;
    /*margin-right: 10px;*/
    /*background: #f5f5f5;*/
    /*background: #666;*/
    background: #778899;
    line-height: 24px;
    font-size: 10px;
    /*color: #666;*/
    color: white;
    text-transform: uppercase;
    font-weight: bold;
    opacity:0.5;
  }

  .card-1,.card-2,.card-3,.card-4,.card-5,.card-6,.card-7,.card-8,.card-9 {
    background-color: white;
    box-shadow: 0px 5px 20px #555;
    margin-top: 20px;
    margin-bottom: 10px;
    position: relative;
  }

  .card-image {
    height: 200px;
    position: relative;
    overflow: hidden;
  }

  .card-image img {
    width: 100%;
    height:100%;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    filter: grayscale(1);
    transition-property: filter width;
    transition-duration: .3s;
    // opacity: 0.8;
  }

  .card-1:hover,.card-4:hover,.card-7:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: left;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-2:hover,.card-5:hover,.card-8:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }

  .card-3:hover,.card-6:hover,.card-9:hover {
    visibility: visible;
    opacity: 1;
    transform:scale(3,3);
    transform-origin: right;
    z-index:100;
    .card-image img {filter: grayscale(0);}
  }


</style>

app/views/pages/faqs.html.erb
<% provide(:title, 'FAQs') %>

<h1>Pages#faqs</h1>
<p>Find me in app/views/pages/faqs.html.erb</p>

app/views/pages/home.html.erb
<%# provide(:title, 'Home') %>
<% content_for :meta_title, "Home | #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_image, "#{DEFAULT_META["meta_image"]}" %>

<!-- Add a parallax background and a banner image -->
<div class="parallax1">
  <div class="banner">
  <div class="banner-content text-center">
    <h1>Grow Your Pharmacy business by Improving Medicines Management in Care</h1>
    <!-- <p>Caremeds Pharma&nbsp; | &nbsp;Caremeds Home Manager&nbsp; | &nbsp;Caremeds eMAR&nbsp; | &nbsp;MultiMeds Blister</p> -->
    <div class="banner-icons">
      <%= link_to pharmacy_path do %>
        <%= image_tag "icons/pharmacy.png" %>
      <% end %>
      <%= link_to careproviders_path do %>
        <%= image_tag "icons/papermars.png" %>
        <%= image_tag "icons/emar.png" %>
        <%= image_tag "icons/multimeds.png" %>
        <%= image_tag "icons/careproviders.png" %>
      <% end %>
    </div>

    <div class="fadeInLeft">
      <p class="content">For more than 30,000 Residents in Care</p>
      <p class="content">In more than 2000 Care Providers</p>
      <p class="content">Generating 250,000 Prescription items each month</p>
    </div>
    <!-- <br><br><br><br><br><br> -->
    <!-- <a class="btn btn-success btn-lg">Contact Now</a> -->
  </div>
  </div>
</div>
<!--
<div class="container">
  <div class="row text-center">
    <h1>Who are you?</h1>
  </div>
  <div class="row text-center pad">

      <%#= link_to "Pharmacy", pages_pharmacy_path, class: "btn btn-xlg black-button" %>

      <%#= link_to "Care Provider", pages_careproviders_path, class: "btn btn-xlg white-button" %>

  </div>
</div>
-->

<!-- <div class="white-bg"> -->
  <div class="container">
    <div class="row pad-top pad-bot">
      <div class="col-xs-12">

        <div class="text-center lightslategray">
          <br><br>
          <p><b>CareMeds</b> is a technology company developing <b>innovative applications</b> that change the way <b>pharmacy</b> and <b>care providers</b> manage their patients and residents medications</p>
          </br>
          <p>Our customers are both <b>pharmacies and care providers</b> with a common goal. They strive to achieve the best possible outcomes for their patients and residents by delivering a person centred medication management solution. The combination of CareMeds systems with the patented MultiMeds blister deliver this.</p>
          <br>
          <p>We put the <b>person</b> at the centre of everything we do and share access to the <b>Pharmacy</b> and <b>Care Provider</b>.</p>
        </div>
      </div>
      </br>
    </div>
  </div>
<!-- </div> -->

<div class="background-color">
  <div class="container">
    <div class="row">
      <br>
      <p class="text-center lightslategray"><b>CareMeds</b> is the only <b>Person Centered System</b> that gives access to <b>ONE PERSON RECORD</b> for both <b>Pharmacy</b> and <b>Care Provider</b></p>
      <br>
        <!-- <div class="col-xs-12 col-sm-8 col-sm-offset-2 text-center"> -->
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-center">
          <div class="graph">
            <%= image_tag "charts/homepage_solution.png" %>
          </div>
          <br>
        </div>
    </div>
  </div>
</div>

<!-- <div class="container lightslategray">

  <div class="row pad-top">
    <div class="col-xs-12 col-md-4">
      <div class="icon-block">
        <h2 class="text-center brown-text"><%#= image_tag "icons/pharmacy.png" %></h2>
        <p class="text-center">
          It starts in <b>Pharmacy</b> with the most advanced <b>web based dispensing system</b> for managed care patients.
        </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-block">
        <h2 class="text-center brown-text"><%#= image_tag "icons/careproviders.png" %></h2>
        <p class="text-center">
          There are currently over <b>500 care providers</b> using <b>CareMeds MAR charts</b>. The charts are unparalleled in this market.
        </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-block">
        <h2 class="text-center brown-text"><%#= image_tag "icons/papermars.png" %></h2>
        <p class="text-center">
          Our <b>5</b> Charts in medication administration are <b>MAR, PRN, Insulin, Topical</b> and <b>Warfarin Charts</b>.
        </p>
      </div>
    </div>
  </div>
  <div class="row pad-bot">
    <div class="col-xs-12 col-md-4">
      <div class="icon-block">
        <h2 class="text-center brown-text"><%#= image_tag "icons/emar.png" %></h2>
        <p class="text-center">
          <b>eMAR</b> solution that seemlessly links with both the <b>Pharmacy system</b> and the <b>Care home system</b>. <b>Android</b> based software running on <b>7"</b> and <b>10" tablets</b>.
        </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-block">
        <h2 class="text-center brown-text"><%#= image_tag "icons/multimeds.png" %></h2>
        <p class="text-center">
          <b>Personalized removable medication pods</b> printed with <b>Resident Name, Drug Name, Dose, Time</b> and <b>Date</b>. For use in both the <b>Community</b> & <b>Carehome setting</b>.
        </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-block">
        <h2 class="text-center brown-text"><%#= image_tag "icons/caremeds.png" %></h2>
        <p class="text-center">
          Whether you are a <b>pharmacy</b> looking to improve your offer to the <b></b>managed care sector, or a <b>care provider</b> looking to improve <b>compliance and safety</b>, please get in <b>touch </b>to see how we can <b>help</b>.
        </p>
      </div>
    </div>
</div>
</div> -->

<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="text-center pad-top pad-bot">
        <p>
            It starts in Pharmacy with the most advanced web based dispensing system for managed care patients. Our customers are specialist pharmacy providers to the managed care sector, and the reason they use CareMeds is because they recognise that standard pharmacy systems fall short when meeting the compliance and saftey needs of this sector.
          </p>

          <p>
            There are currently over 500 care providers using CareMeds MAR charts. The charts are unparalleled in the market
          </p>

          <p>
            In addition to these unique Medication Administration Charts, we have also developed the only working eMAR solution that seemlessly links with both the Pharmacy system and the Care home system with TWO-WAY communication. We put the patient at the centre of everything we do and share access to the various stakeholders Pharmacy, Care Provider, and even the GP.
          </p>

          <p>
            CareMeds eMAR is Android based and runs on 7" and 10" tablets.
          </p>

          <p>
            Whether you are a pharmacy looking to improve your offer to the managed care sector, or a care provider looking to improve compliance and safety, please get in touch to see how we can help.
          </p>
      </div>
    </div>
  </div>
</div> -->

<div class="parallax2"></div>
<div class="white-bg">

<div class="container lightslategray">

  <div class="row pad-top pad-bot">
    <div class="col-xs-12 col-md-4">
      <div class="icon-block text-center">
        <h2 class="darkgray"><i class="fa fa-plus-square"></i></h2>
        <h4 class="darkgray">For Your Pharmacy</h4>
        <hr class="style-two">
        <h5><b>Stand Out in the Crowd</b></h5>
        <p>
          In this ever increasing competitive market, pharmacy owners need every possible competitive advantage they can leverage to ensure their business propsers.
          <br><br><br>
          <strong>CareMeds</strong> offers such an advantage.
        </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-block text-center">
        <h2 class="darkgray"><span class="glyphicon glyphicon-bed"></h2>
        <h4 class="darkgray">For Your Carehome</h4>
        <hr class="style-two">
        <h5><b>Safe and Simple Drug Rounds</b></h5>
        <p>
          Medication rounds made easy, that’s the best way to describe CareMeds medicines management system. Dynamic MAR Charts and intuitive eMAR from your pharmacy provider. <br>
          <br><br>
          <strong>CareMeds</strong> safe, simple and efficient
        </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-block text-center">
        <h2 class="darkgray"><span class="glyphicon glyphicon-home"></span></h2>
        <h4 class="darkgray">For the Community</h4>
        <hr class="style-two">
        <h5><b>Are you a Homecare provider?</b></h5>
        <p>
          Medicines administration in the community is no longer just about prompting, ensure your carers and service users are protected with a safe and secure medication management system.
          <br><br>
          <strong>CareMeds</strong> MAR Charts make it clear
        </p>
      </div>
    </div>
  </div>
</div>
</div>

<%= render "shared/form", contact: @contact %>


<!-- <script>

    var quotes = [
        "500 care providers using CareMeds MAR charts",
        "CareMeds is the only the market leading medication management software system",
        "Independent pharmacy owners using CareMeds now provide medications to over 10,000 residents in the managed care sector",
        ];

        var i = 0;

        setInterval(function() {
            $(".fadeInLeft").html(quotes[i]);
            if (i == quotes.length)
                i=0;
            else
                // $("<p style='display: none;'>"+quotes[i]+"</p>").appendTo('.fadeInLeft').delay(1000*i).fadeIn(500);
                i++;


        }, 2 * 1750);


</script> -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Caremeds-logo.jpeg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <% if user_signed_in? %>

      <div class="hidden-xs hidden-sm">
        <%= link_to "Dashboard", home_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "New Blog", new_news_blog_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "All Blogs", news_blogs_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

      <div class="dropdown hidden-xs hidden-sm">
        <%= link_to "Page Tabs", class: "navbar-wagon-item navbar-wagon-link", "data-toggle" => "dropdown" do %>
          Page Tabs <span class="caret"></span>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li> <%= link_to "Home", home_path %></li>
          <li> <%= link_to "Pharmacy", pharmacy_path %></li>
          <li> <%= link_to "Care Providers", careproviders_path %></li>
          <li> <%= link_to "Contact Us", contactus_path%></li>
          <li> <%= link_to "News", news_path %></li>
        </ul>
      </div>

      <div class="navbar-wagon-item hidden-xs hidden-sm">
        <div class="dropdown">
          <%= image_tag "https://png.icons8.com/ios/100/5A6064/circled-#{current_user.first_name[0]}.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <div class="hidden-xs hidden-sm">
          <%= link_to "Home", home_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Pharmacy", pharmacy_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Care Providers", careproviders_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%#= link_to "EMAR", emar_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Contact Us", contactus_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%#= link_to "FAQs", faqs_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "News", news_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%#= link_to "Updates", updates_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

    <% end %>

    <!-- For use of drop down in desktop mode -->
    <!-- <div class="dropdown hidden-xs hidden-sm">
      <a class="navbar-wagon-item navbar-wagon-link" data-toggle="dropdown">More..<span class="caret"></span></a>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%#= link_to "Contact Us", contactus_path %></li>
        <li><%#= link_to "FAQs", faqs_path %></li>
        <li class="divider"></li>
        <li class="dropdown-header">SYSTEM</li>
        <li><%#= link_to "News", news_path %></li>
        <li><%#= link_to "Updates", updates_path %></li>
      </ul>
    </div> -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu multi-level dropdown-menu-right navbar-wagon-dropdown-menu">

        <li> <%= link_to "Home", home_path %></li>
        <li> <%= link_to "Pharmacy", pharmacy_path %></li>
        <li> <%= link_to "Care Providers", careproviders_path %></li>
        <li> <%#= link_to "EMAR", emar_path %></li>
        <li> <%= link_to "Contact Us", contactus_path%></li>
        <li> <%= link_to "News", news_path %></li>
        <% if user_signed_in? %>
        <li class="divider"></li>
        <li><%= link_to "Dashboard", home_path %></li>
        <li><%= link_to "New Blog", home_path %></li>
        <li><%= link_to "All Blogs", pharmacy_path %></li>
        <li class="divider"></li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
        <% end %>
        <!-- For use of sub drop down in mobile mode -->
        <!-- <li class="dropdown-submenu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown</a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
          </ul>
        </li> -->
      </ul>
    </div>
  </div>
</div>

app/views/sitemaps/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc><%= @host %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{home_path}" %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{pharmacy_path}" %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{careproviders_path}" %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{contactus_path}" %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{news_path}" %></loc>
   </url>
   <% @news_blogs.each do |nb| %>
     <url>
        <loc><%= "#{@host}/news_show/#{nb.id}" %></loc>
     </url>
   <% end %>
</urlset>